anchoreGlobal:
  defaultAdminPassword: foobar
  imagePullPolicy: IfNotPresent

anchoreEnterpriseGlobal:
  enabled: true
  image: docker.io/nextlinux/enterprise-dev:nightly
  imagePullPolicy: Always

anchoreEnterpriseUi:
  enabled: false

anchore-ui-redis:
  enabled: false

postgresql:
  resources:
    limits:
      cpu: 2
      memory: 2Gi

anchore-feeds-db:
  enabled: false

anchoreApi:
  service:
    type: NodePort
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 100m

anchoreAnalyzer:
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 100m

anchoreCatalog:
  resources:
    limits:
      cpu: 4
    requests:
      cpu: 100m

anchorePolicyEngine:
  resources:
    limits:
      cpu: 4
    requests:
      cpu: 100m

anchoreSimpleQueue:
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 100m

anchoreEnterpriseFeeds:
  enabled: false
